services:
  app:
    image: php:8.3.20-apache
    container_name: collab-app
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.collab-app
    ports:
      - "8080:80"
    volumes:
      - "./:/var/www/html"
    networks:
      - collab-network
    env_file:
      - .env

  db:
    image: mysql:5.7
    container_name: collab-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: main
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - collab-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: collab-phpmyadmin
    environment:
      PMA_HOST: ${PMA_HOST}
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - collab-network

networks:
  collab-network:
    driver: bridge
